"""BareTensor native extension (bootstrap)"""

from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class Tensor:
    @property
    def shape(self) -> list[int]: ...

    @property
    def strides(self) -> list[int]: ...

    def ndim(self) -> int: ...

    def numel(self) -> int: ...

    def is_contiguous(self) -> bool: ...

    def contiguous(self) -> Tensor: ...

    def view(self, shape: Sequence[int]) -> Tensor: ...

    def reshape(self, shape: Sequence[int]) -> Tensor: ...

    def permute(self, dims: Sequence[int]) -> Tensor: ...

    def transpose(self, dim0: int, dim1: int) -> Tensor: ...

    @property
    def T(self) -> Tensor: ...

    @property
    def mT(self) -> Tensor: ...

    def matmul(self, tensor2: Tensor) -> Tensor: ...

    def __matmul__(self, arg: Tensor, /) -> Tensor: ...

    def numpy(self) -> object: ...

    @overload
    def __add__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __add__(self, arg: float, /) -> Tensor: ...

    @overload
    def __sub__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __sub__(self, arg: float, /) -> Tensor: ...

    @overload
    def __mul__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __mul__(self, arg: float, /) -> Tensor: ...

    @overload
    def __truediv__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __truediv__(self, arg: float, /) -> Tensor: ...

def full(shape: Sequence[int], fill_value: float) -> Tensor: ...

def zeros(shape: Sequence[int]) -> Tensor: ...

def ones(shape: Sequence[int]) -> Tensor: ...

def matmul(input: Tensor, other: Tensor) -> Tensor: ...

def tensor(array: Annotated[NDArray[numpy.float32], dict(order='C', device='cpu', writable=False)]) -> Tensor: ...
