"""BareTensor native extension (bootstrap)"""

from collections.abc import Sequence
from typing import Annotated, overload

import numpy
from numpy.typing import NDArray


class Tensor:
    @property
    def shape(self) -> list[int]: ...

    @property
    def strides(self) -> list[int]: ...

    def dim(self) -> int: ...

    def numel(self) -> int: ...

    def is_contiguous(self) -> bool: ...

    @overload
    def __add__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __add__(self, arg: float, /) -> Tensor: ...

    @overload
    def __sub__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __sub__(self, arg: float, /) -> Tensor: ...

    @overload
    def __mul__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __mul__(self, arg: float, /) -> Tensor: ...

    @overload
    def __truediv__(self, arg: Tensor, /) -> Tensor: ...

    @overload
    def __truediv__(self, arg: float, /) -> Tensor: ...

def full(arg0: Sequence[int], arg1: float, /) -> Tensor: ...

def zeros(arg: Sequence[int], /) -> Tensor: ...

def ones(arg: Sequence[int], /) -> Tensor: ...

def tensor(arg: Annotated[NDArray[numpy.float32], dict(order='C')], /) -> None: ...
