from collections.abc import Iterator, Sequence
import builtins

from numpy.typing import ArrayLike

from bt._C import Tensor as Tensor

from . import functional as functional

def Parameter(data: Tensor | ArrayLike) -> Tensor: ...

class Module:
    training: builtins.bool
    def __init__(self) -> None: ...
    def forward(self, *args: object, **kwargs: object) -> Tensor: ...
    def __call__(self, *args: object, **kwargs: object) -> Tensor: ...
    def parameters(self) -> Iterator[Tensor]: ...
    def train(self, mode: builtins.bool = True) -> "Module": ...
    def eval(self) -> "Module": ...

class Linear(Module):
    in_features: int
    out_features: int
    weight: Tensor
    bias: Tensor | None
    def __init__(self, in_features: int, out_features: int, bias: builtins.bool = True) -> None: ...
    def reset_parameters(self) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class Embedding(Module):
    num_embeddings: int
    embedding_dim: int
    weight: Tensor
    def __init__(self, num_embeddings: int, embedding_dim: int) -> None: ...
    def reset_parameters(self) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...

class LayerNorm(Module):
    normalized_shape: tuple[int, ...]
    eps: float
    elementwise_affine: builtins.bool
    weight: Tensor | None
    bias: Tensor | None
    def __init__(
        self,
        normalized_shape: int | Sequence[int],
        eps: float = 1e-5,
        elementwise_affine: builtins.bool = True,
    ) -> None: ...
    def reset_parameters(self) -> None: ...
    def forward(self, input: Tensor) -> Tensor: ...
